# Generated by Django 4.2.7 on 2023-12-03 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="spouse_name",
        ),
    ]
