# Generated by Django 4.2.7 on 2023-12-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_customuser_spouse_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                default="Mateusz Kolimaga", max_length=150, verbose_name="name"
            ),
            preserve_default=False,
        ),
    ]
