# Generated by Django 4.2.7 on 2023-12-04 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_customuser_date_of_birth_customuser_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="name",
        ),
    ]
