# Generated by Django 4.2.7 on 2023-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teamexpense",
            old_name="group",
            new_name="team",
        ),
        migrations.AlterField(
            model_name="team",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="team_avatars/"),
        ),
    ]
