# Generated by Django 4.2.7 on 2023-12-11 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_rename_group_teamexpense_team_alter_team_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamexpense",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
