# Generated by Django 4.2.7 on 2023-12-18 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0004_teammember_teamexpensecomment_grouptransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamexpense",
            name="users_settled",
            field=models.ManyToManyField(
                default=[
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses_paid",
                        to=settings.AUTH_USER_MODEL,
                    )
                ],
                related_name="expenses_settled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
