# Generated by Django 4.2.7 on 2023-12-18 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0006_alter_grouptransaction_text_delete_teammember"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouptransaction",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="grouptransaction",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
