# Generated by Django 4.2.7 on 2024-01-04 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0009_alter_groupmessage_team_teaminvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="teaminvitation",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TeamDebtReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_user_email", models.EmailField(max_length=254)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="teams.team",
                    ),
                ),
            ],
        ),
    ]
