# Generated by Django 4.2.7 on 2024-01-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0010_teaminvitation_accepted_teamdebtreminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamexpense",
            name="currency",
            field=models.CharField(
                choices=[("$", "$")],
                default="PLN",
                max_length=3,
                verbose_name="currency",
            ),
        ),
    ]
