# Generated by Django 4.2.7 on 2024-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0011_alter_teamexpense_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamexpense",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD")],
                default="USD",
                max_length=3,
                verbose_name="currency",
            ),
        ),
    ]
