# Generated by Django 4.2.7 on 2023-12-14 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0002_alter_personalexpense_attachments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalexpense",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="personalincome",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
