# Generated by Django 4.2.7 on 2024-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0004_alter_personalexpense_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalexpense",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD")],
                default="USD",
                max_length=3,
                verbose_name="currency",
            ),
        ),
        migrations.AlterField(
            model_name="personalincome",
            name="currency",
            field=models.CharField(
                choices=[("USD", "USD")],
                default="USD",
                max_length=3,
                verbose_name="currency",
            ),
        ),
    ]
